exports.LOG_PREFIXES = Object.freeze({
  SERVER_START: '[SERVER START]',
  DB_POOL: '[DATABASE POOL]',
  DB_CREATE: '[DATABASE CREATION]',
  DB_UPDATE: '[DATABASE RETRIEVE]',
  START_ANALYSIS: '[AI ANALYSIS START]',
});

exports.JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
});
