exports.LOG_PREFIXES = Object.freeze({
  SERVER_START: '[SERVER START]',
  DB_INIT: '[DB INITIALIZATION]',
  DB_POOL: '[DATABASE POOL]',
  DB_CREATE: '[DATABASE CREATION]',
  DB_RETRIEVE: '[DATABASE RETRIEVE]',
  GET_ANALYSIS: '[ANALYSIS RETRIEVE]',
  POST_ANALYSIS: '[ANALYSIS CREATION]',
  LAMBDA_INVOKE: '[LAMBDA INVOKE]',
  GET_SPEC_CREATION: '[OPENAPI FROM CURL RETRIEVE]',
  POST_SPEC_CREATION: '[OPENAPI FROM CURL CREATION]',
  GET_ENDPOINT_GUIDE: '[ENDPOINT GUIDE RETRIEVE]',
  POST_ENDPOINT_GUIDE: '[ENDPOINT GUIDE CREATION]',
});

exports.JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
});
