const LOG_PREFIXES = Object.freeze({
  AI_ANALYSIS: '[AI ANALYSIS]',
  OPENAPI_FROM_CURL: '[OPENAPI FROM CURL]',
  ENDPOINT_GUIDE: '[ENDPOINT GUIDE]',
  DB_POOL: '[DATABASE POOL]',
  DB_CREATE: '[DATABASE CREATION]',
  DB_UPDATE: '[DATABASE RETRIEVE]',
});

const JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
});

module.exports = { LOG_PREFIXES, JOB_STATUS };

